version: '3.8'

services:

  example_frontend_ex2_8:
    build: ./example-frontend
    container_name: example_frontend_ex2_8_container
    ports:
      - "5000:5000"
    environment:
      REACT_APP_BACKEND_URL: "http://127.0.0.1:8080/ping"
      # REACT_APP_BACKEND_URL: "http://localhost/api/"

  redis:
    image: redis
    build: .
    ports:
      - "6379:6379"
      
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_USER: "postgres"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  example_backend_ex2_8:
    build: ./example-backend
    container_name: example_backend_ex2_8_container
    ports:
      - "8080:8080"
    environment:
        REQUEST_ORIGIN: "http://127.0.0.1:5000"
        PATH: "/usr/local/go/bin"
        REDIS_HOST: redis
        REDIS_PORT: 6379
        POSTGRES_HOST: db
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DATABASE: "postgres"

  proxy:
    image: nginx
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - example_frontend_ex2_8
      - example_backend_ex2_8
